-- local ls = require("luasnip")
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local fmt = require("luasnip.extras.fmt").fmt
--
-- return {
--   -- Simple function snippet
--   s("def", fmt([[
-- def {}({}):
--     {}
--   ]], {
--     i(1, "function_name"),
--     i(2, "args"),
--     i(0, "pass"),
--   })),
-- }
